local packages = {
    "hyprland",
    "hyprshot",
    "hyprpicker",
    "xdg-desktop-portal-hyprland",
    "xdg-utils",
    "nautilus",
    "file-roller",
    "unzip",
    "unrar",
    "zip",
    "gvfs",
    "7zip",
    "polkit",
    "polkit-gnome",
    "gnome-keyring",
    "whitesur-cursor-theme-git",
    "awww",
    "swaync",
    "waybar-cava-git",
    "satty",
    "fastfetch",
    "kitty",
    "fish",
    "starship",
    "vicinae", -- or rofi
    "ttf-jetbrains-mono-nerd",
    "cava",
    "gpsd",
    "neovim",
    "tree-sitter",
    "tree-sitter-cli",
    "noto-fonts",
    "noto-fonts-emoji",
    "papirus-icon-theme",
    "papirus-folders",
    "ttf-liberation",
    "adw-gtk-theme",
    "gtk-engine-murrine",
    "nwg-look",
    "qt6ct",
    "kvantum",
    "qt6gtk2",
    "qt5-wayland",
    "qt6-wayland",
    "qt5-styleplugins",
    "wlogout",
    "wl-clipboard",
    -- others
    "brightnessctl",
    "overskride-bin",
    "helium-browser-bin",
    "tree",
    "vesktop",
    "btop",
    "pavucontrol",
    "sassc",
    "cmatrix"
}

return {
    description = "Hyprland rice module",
    dotfiles_sync = true,
    packages = packages,
}
