# The basic colors
foreground              #cdd6f4
background              #1e1e2e
selection_foreground    #1e1e2e
selection_background    #585b70

# Cursor colors
cursor                  #f5e0dc
cursor_text_color       #1e1e2e

# URL underline color when hovering with mouse
url_color               #89b4fa

# Kitty window border colors
active_border_color     #89b4fa
inactive_border_color   #585b70
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1e1e2e
active_tab_background   #89b4fa
inactive_tab_foreground #a6adc8
inactive_tab_background #181825
tab_bar_background      #1e1e2e

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #89b4fa
mark2_foreground #1e1e2e
mark2_background #f5c2e7
mark3_foreground #1e1e2e
mark3_background #a6e3a1

# The 16 terminal colors

# black
color0  #45475a
color8  #585b70

# red
color1  #f38ba8
color9  #f37799

# green
color2  #a6e3a1
color10 #89d88b

# yellow
color3  #f9e2af
color11 #ebd391

# blue
color4  #89b4fa
color12 #74a8fc

# magenta
color5  #f5c2e7
color13 #f2aede

# cyan
color6  #94e2d5
color14 #6bd7ca

# white
color7  #a6adc8
color15 #bac2de
