# The basic colors
foreground              #c5c9c5
background              #181616
selection_foreground    #181616
selection_background    #c5c9c5

# Cursor colors
cursor                  #c8c093
cursor_text_color       #181616

# URL underline color when hovering with mouse
url_color               #7fb4ca

# Kitty window border colors
active_border_color     #7fb4ca
inactive_border_color   #a6a69c
bell_border_color       #e6c384

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #181616
active_tab_background   #8ea4a2
inactive_tab_foreground #c8c093
inactive_tab_background #0d0c0c
tab_bar_background      #181616

# Colors for marks (marked text in the terminal)
mark1_foreground #181616
mark1_background #7fb4ca
mark2_foreground #181616
mark2_background #938aa9
mark3_foreground #181616
mark3_background #87a987

# The 16 terminal colors

# black
color0  #0d0c0c
color8  #a6a69c

# red
color1  #c4746e
color9  #e46876

# green
color2  #8a9a7b
color10 #87a987

# yellow
color3  #c4b28a
color11 #e6c384

# blue
color4  #8ba4b0
color12 #7fb4ca

# magenta
color5  #a292a3
color13 #938aa9

# cyan
color6  #8ea4a2
color14 #7aa89f

# white
color7  #c8c093
color15 #c5c9c5
